name: Run Tests
on: 
  push:
    branches: [main]
  schedule:
     - cron: '0 18 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.14.0
        - name: Install
          run: npm install
        - name: Tests
          run: npm run wdio
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
